import { Metadata } from 'next';
import { Check } from 'lucide-react';
import Link from 'next/link';
import PremiumHero from '@/components/premium-hero';
import CTABanner from '@/components/cta-banner';
import FAQSection from '@/components/faq-section';
import Reveal from '@/components/reveal';
import { generateMetadata as genMeta, generateServiceSchema, generateFAQSchema, generateBreadcrumbSchema, baseUrl } from '@/lib/seo';

const PATH = '/services/audit-support/australia';
export const metadata: Metadata = genMeta({ title: 'Australian Audit Support for Accounting Teams | Accounstone', description: 'Australian audit support for schedules, reconciliations, evidence and working papers, organised around the engaged auditor’s review process.', path: PATH });
const overview = "Audit preparation can become a coordination problem: schedules are in different places, evidence requests keep changing and the people who know the numbers are also trying to keep the day-to-day work moving. We support documentation, reconciliation and defined preparation work for Australian businesses, while the engaged registered auditor retains assurance responsibility, professional judgement and the audit opinion.";
const benefits = ['Working-paper and schedule preparation before fieldwork', 'Reconciliations and supporting-document organisation', 'Evidence-request tracking and open-item follow-up', 'Testing support where defined by the engaged audit team', 'Preparation of documentation around Australian statutory accounts work', 'Flexible capacity during audit periods without changing the audit relationship'];
const retained = ['Audit opinion and professional judgement', 'Final audit conclusions and assurance decisions', 'Direction of audit procedures by the engaged auditor', 'Client-facing audit conclusions and statutory responsibilities'];
const faqs = [
  { question: 'Do you issue the audit opinion?', answer: 'No. The engaged registered auditor remains responsible for the audit opinion and professional judgement. We support preparation, schedules, documentation and defined testing work.' },
  { question: 'Can you help before Australian audit fieldwork begins?', answer: 'Yes. Organising reconciliations, schedules, evidence and open items before fieldwork can reduce the time the audit team spends waiting for information or chasing routine support.' },
  { question: 'Can you work with our existing Australian audit firm?', answer: 'Yes. The support can follow the formats, requests and review process used by the engaged audit team rather than introducing a separate reporting system.' },
  { question: 'Can you help with ASIC or Corporations Act audit preparation?', answer: 'We can support underlying schedules and documentation. Your accountant and auditor should confirm the company-specific statutory requirements and audit position.' },
];
const faqSchema = generateFAQSchema(faqs);
const serviceSchema = generateServiceSchema({ name: 'Audit Support Services for Australian Businesses', description: overview, slug: 'audit-support/australia', basePath: '/services/', areaServed: ['AU'] });
const breadcrumbSchema = generateBreadcrumbSchema([{ name: 'Home', url: baseUrl }, { name: 'Services', url: `${baseUrl}/services` }, { name: 'Audit Support', url: `${baseUrl}/services/audit-support` }, { name: 'Australia', url: `${baseUrl}${PATH}` }]);
export default function AuditSupportAUPage() {
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    <PremiumHero subtitle="Audit Support for Australian Businesses" title="Australian Audit Support Services" description="Schedules, evidence and documentation support built around your engaged auditor's review process." cta={{ text: 'Get Started', href: '/contact' }} ctaSecondary={{ text: 'View All Services', href: '/services' }} background="primary-gradient" />
    <nav aria-label="Breadcrumb" className="w-full px-6 md:px-8 pt-6 bg-white"><ol className="max-w-4xl mx-auto flex flex-wrap items-center gap-2 text-sm text-muted"><li><Link href="/">Home</Link></li><li aria-hidden="true">/</li><li><Link href="/services">Services</Link></li><li aria-hidden="true">/</li><li><Link href="/services/audit-support">Audit Support</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="text-primary font-medium">Australia</li></ol></nav>
    <section className="w-full py-8 md:py-12 px-6 md:px-8 bg-white"><Reveal className="max-w-4xl mx-auto space-y-6"><><span className="text-sm font-semibold tracking-wide uppercase text-accent">Overview</span><h2 className="text-2xl md:text-3xl font-bold text-primary text-balance">Make the Australian Audit File Easier to Work Through</h2><p className="text-lg text-muted leading-relaxed">{overview}</p></></Reveal></section>
    <section className="w-full py-8 md:py-12 px-6 md:px-8 bg-input"><div className="max-w-5xl mx-auto"><Reveal className="text-center space-y-4 mb-16"><><span className="text-sm font-semibold tracking-wide uppercase text-accent">Scope</span><h2 className="text-2xl md:text-3xl font-bold text-primary text-balance">What Can Be Prepared Before Review</h2></></Reveal><ul className="grid grid-cols-2 md:grid-cols-2 gap-3 md:gap-6">{benefits.map((b, i) => <Reveal key={i}><li className="flex items-start gap-2 sm:gap-4 p-3.5 sm:p-6 bg-white rounded-xl border border-border/70"><Check className="shrink-0 text-accent w-4 h-4 sm:w-5 sm:h-5 mt-0.5 sm:mt-0" aria-hidden="true" /><p className="text-foreground text-sm sm:text-base leading-5 sm:leading-relaxed">{b}</p></li></Reveal>)}</ul></div></section>
    <section className="w-full py-8 md:py-12 px-6 md:px-8 bg-white"><div className="max-w-5xl mx-auto rounded-2xl bg-primary text-white p-8 md:p-10"><span className="text-sm font-semibold uppercase tracking-wide text-white/70">Australian workflow boundary</span><h2 className="text-3xl font-bold mt-3 mb-6">Preparation can move. Assurance stays with the auditor.</h2><p className="text-white/85 leading-7 mb-6">Schedules, reconciliations, evidence and defined testing support can be prepared around the audit team's process. The engaged auditor retains assurance responsibility, professional judgement and the audit opinion.</p><ul className="grid md:grid-cols-2 gap-4">{retained.map((item, i) => <li key={i} className="flex items-start gap-3"><Check className="w-5 h-5 text-white shrink-0" aria-hidden="true" /><span className="text-white/85 leading-6">{item}</span></li>)}</ul></div></section>
    <section className="w-full py-16 px-6 md:px-8 bg-input"><div className="max-w-5xl mx-auto text-center"><h2 className="text-3xl font-bold text-primary mb-5">Keep the Australian service cluster connected</h2>
        <div className="mb-5 p-4 bg-white rounded-xl border border-border/70 flex flex-wrap items-center justify-center gap-3">
          <span className="text-xs font-bold uppercase tracking-wide text-muted">Same service, other regions:</span>
          <Link href="/services/audit-support/united-states" className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-input border border-border text-sm text-primary font-medium hover:bg-border transition-colors">🇺🇸 United States</Link>
          <Link href="/services/audit-support/united-kingdom" className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-input border border-border text-sm text-primary font-medium hover:bg-border transition-colors">🇬🇧 United Kingdom</Link>
        </div>
        <div className="flex flex-wrap justify-center gap-3"><Link href="/markets/australia" className="px-4 py-2 rounded-lg bg-white text-primary font-medium hover:bg-border transition-colors">Australia Market Overview</Link><Link href="/services/bookkeeping/australia" className="px-4 py-2 rounded-lg bg-white text-primary font-medium hover:bg-border transition-colors">Australian Bookkeeping</Link><Link href="/services/tax-preparation/australia" className="px-4 py-2 rounded-lg bg-white text-primary font-medium hover:bg-border transition-colors">Australian Tax Preparation</Link><Link href="/technology/xero" className="px-4 py-2 rounded-lg bg-white text-primary font-medium hover:bg-border transition-colors">Xero</Link><Link href="/technology/myob" className="px-4 py-2 rounded-lg bg-white text-primary font-medium hover:bg-border transition-colors">MYOB</Link></div></div></section>
    <FAQSection subtitle="Questions" items={faqs} columns={2} /><CTABanner title="Preparing for Australian Audit Fieldwork?" description="Tell us whether the pressure sits in schedules, evidence, reconciliations or open-item follow-up." cta={{ text: 'Start a Conversation', href: '/contact' }} background="primary" />
  </main>;
}
